"""Revision after the two journal-style reviews (2026-10-04).
Rewrites title, highlights, abstract, Section 3 and Section 5 wholesale,
inserts method details and a data-quality/reproducibility subsection, and
edits the introduction and discussion in place."""
import os
import re

PAPER = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
p = os.path.join(PAPER, 'manuscript.md')
s = open(p, encoding='utf-8').read()
missing = []


def rep(old, new, count=1):
    global s
    if old not in s:
        missing.append(old[:90])
        return
    s = s.replace(old, new, count)


def replace_between(start_marker, end_marker, new_text):
    global s
    a = s.index(start_marker)
    b = s.index(end_marker, a)
    s = s[:a] + new_text + s[b:]


# ---------------------------------------------------------------- title
rep("# What a farm's own records can and cannot teach a planning-grade crop model: a single-farm evaluation of calibration and a within-field fertility index in an open-source QGIS plugin",
    "# Limits of calibrating a simple crop model and a within-field productivity index from operational farm records: a single-farm diagnostic evaluation in the open-source QGIS plugin GeoDataFarm")
rep("Target journal: Computers and Electronics in Agriculture. Draft 0.2 after internal review, 2026-09-26.",
    "Target journal: Computers and Electronics in Agriculture. Draft 0.4 after external review, 2026-10-04.")

# ---------------------------------------------------------------- highlights
replace_between("## Highlights\n", "## Abstract", """## Highlights

- A single-farm diagnostic evaluation of a simple crop model in an open-source FMIS
- Under the plugin's implemented default, calibration left a 49 % error and a 21 t/ha bias
- Treating a missing nutrient record as zero applied caused parameter-bound solutions
- The same-variety mean out-predicted the calibrated model in this single-farm dataset
- Equal-weight soil layers removed the weak signal carried by the previous yield map

""")

# ---------------------------------------------------------------- abstract
replace_between("## Abstract\n", "Keywords:", """## Abstract

Farm management information systems (FMIS) accumulate years of records that are seldom used for prediction, while the crop simulators that could use them need inputs a farmer does not have. This single-farm diagnostic study asks what the operational records of one commercial irrigated potato farm in southern Sweden can teach a simple, planning-grade crop model embedded in the open-source QGIS plugin GeoDataFarm, meaning a model intended for seasonal planning and scenario comparison rather than research-grade simulation, and how the same records behave in the plugin's within-field productivity index. Twenty-two potato field-years from 2015 to 2025, with 48 variety-level yield observations, were evaluated by leave-one-field-year-out cross-validation against literature defaults, a training-set farm mean and a training-set same-variety mean, with learning curves, bootstrap resampling of parameters and pre-specified sensitivity runs; the index was scored on 21 consecutive-year field pairs. Under the plugin's implemented default, which models an unlogged nutrient as zero applied, calibration reduced the typical error from 78 % to 49 % of the mean yield but left a 21 t/ha bias, because the unlogged potassium floor capped every estimate and drove potential yield to its search bound. In a post hoc diagnostic variant that treats an unlogged nutrient as unknown, the error fell from 58 % to 31 %, still above the farm mean's 27 %; the same-variety mean, at 22 %, was the strongest predictor evaluated, and refitting potential yield per variety only brought the model level with the farm mean. Potential yield was comparatively stable under resampling (90 % of bootstrap fits within 82 to 97 t/ha) whereas the nitrogen parameters spanned most of their ranges. The previous season's yield map ranked next-season yield with a median Spearman correlation of 0.18; the plugin's equal-weight combination with soil layers performed worse in 12 of 13 pairs, and a sign-aware weighting recovered approximately the yield-only level without demonstrating added value from the soil layers. In this dataset the operational data semantics, how a missing record is interpreted and how heterogeneous layers are combined, determined what the models could identify; the results are case-study evidence, not a general evaluation of crop models in potato.

""")

# ---------------------------------------------------------------- introduction
rep("Little published work describes a small mechanistic model driven by the data a farmer already logs and calibrated by the data owner inside the software the farmer already uses.",
    "Little published work describes a small mechanistic model driven by the data a farmer already logs and calibrated by the data owner inside the software the farmer already uses. We call such a model planning-grade: it is meant to rank seasons and management options and to attribute a season's shortfall to water or nutrients, not to forecast yield to research accuracy. A model can be weak at out-of-sample yield prediction and still be useful for that kind of comparison; this study tests only the prediction side, which is the part the records allow us to test.")
rep("""- O1. Quantify the gain from farm-calibrating a three-parameter model against a farm's own harvest history, compared with literature defaults and simple baselines, and how that gain depends on the number of training seasons.
- O2. Assess whether the three fitted parameters are stable across cross-validation folds.
- O3. Test whether a percentile-rank fertility index built from the previous season's yield and soil sampling predicts the next season's within-field yield pattern better than single sources.""",
    """- O1. Quantify the gain from farm-calibrating a three-parameter model against a farm's own harvest history, compared with literature defaults and simple baselines, and how that gain depends on the number of training seasons. Hypothesis: calibration reduces the error of the defaults by at least 20 % and beats the training-set farm mean.
- O2. Assess whether the three fitted parameters are stable under resampling of field-years. Hypothesis: all three are determined to within a fraction of their search ranges.
- O3. Test whether the plugin's percentile-rank index, built from the previous season's yield map and the field's soil layers, ranks the next season's within-field yield better than the yield map alone. Hypothesis: adding soil layers improves the ranking.

The two analyses use different units, data and literatures, and are kept in one paper for a single reason: both are functions of the same FMIS applied to the same records, and both turn out to be governed by how the software interprets what the records do not say, a missing nutrient application in the model and the direction of a soil layer in the index. The paper is therefore framed as a single-farm diagnostic case study of how operational data semantics and incompleteness constrain model-based decision support, with the crop model and the index as two instances.""")

# ---------------------------------------------------------------- methods details
rep("Weather is fetched per field centroid from the Open-Meteo historical archive, which serves reanalysis-based hourly data globally (Zippenfenig, 2023), aggregated to daily mean temperature, precipitation and reference evapotranspiration.",
    "Weather is fetched per field centroid from the Open-Meteo historical archive (Zippenfenig, 2023), which serves the ERA5 and ERA5-Land reanalyses at roughly 9 to 25 km grid spacing, as daily mean temperature, precipitation and reference evapotranspiration in the field's local time zone; no imputation is applied, and a season without weather is skipped.")
rep("Crop development. Daily thermal time is GDD = max(0, Tmean - Tbase),",
    "Season bounds and initial state. A season runs from the logged planting date to the harvest date on file, or to 31 December when only the harvest year is known; on this farm 1100 GDD was reached between 25 July and 29 August in every season, so the late bound only lengthens the weather slice. The soil water store starts the season at field capacity and the nitrogen and potassium pools at zero, so that only logged applications supply nutrients.\n\nCrop development. Daily thermal time is GDD = max(0, Tmean - Tbase),")
rep("The plugin builds one training example per field, harvest year and variety that has real yield data: its own weather slice, planting date, fertiliser and irrigation events, soil values and the field-mean observed yield.",
    "Two units recur throughout the paper. A field-year is one field harvested in one calendar year; it has one weather slice, one planting date, one set of fertiliser and irrigation records and one soil description. A variety observation is the separately recorded yield of one variety within a field-year; a field-year planted with three varieties gives three variety observations that share every model input except the variety label. The plugin builds one training example per variety observation: the field-year's inputs and that variety's mean observed yield from its own part of the field.")
rep("Potato is grown in rotation with winter and spring wheat, barley and oilseed rape;",
    "Yield is the fresh mass recorded by the harvester's yield monitor without correction for dry matter, tare or grading; this limits comparability between varieties and years and is one reason the quality screening of Section 2.8 is needed. Potato is grown in rotation with winter and spring wheat, barley and oilseed rape;")

# algorithm block + variety baseline rules + learning curve details + seed
rep("Two sensitivity runs repeated the cross-validation without the seasons 2015 to 2017, for which no irrigation record exists, and without the three field-years whose observed yields exceed 80 t/ha.",
    """Two pre-specified sensitivity runs repeated the cross-validation without the seasons 2015 to 2017, for which no irrigation record exists, and without the three field-years whose observed yields exceed 80 t/ha; the latter is reported as the quality-screened level of Section 2.8. A third check reads the fitted relative-yield terms of each fold and recombines them multiplicatively instead of by the minimum, without refitting, to show whether the conclusions depend on the Liebig operator.

The cross-validation procedure, including every baseline and fallback rule, is:

- For each of the 22 field-years in turn, hold out all of its variety observations; the remaining observations form the training set.
- Fit the three crop-level parameters on the training set by the plugin's coarse-to-fine grid search. Fit the one-parameter variant (potential yield only) on the same training set.
- Variety-aware variant: for each variety that occurs in at least two training field-years, refit potential yield on that variety's training observations with the crop-level nitrogen parameters held fixed; a held-out observation whose variety does not meet this rule is predicted with the crop-level potential yield.
- Training-set farm mean: the unweighted mean observed yield of all training observations.
- Training-set same-variety mean: the unweighted mean observed yield of the training observations of the same variety, whatever their number; if the variety does not occur in the training set, the training-set farm mean. In this dataset 31 of 48 observations had a same-variety training mean and 17 fell back to the farm mean.
- Predict every held-out observation with every method; the field-year prediction is the unweighted mean over the field-year's variety observations and is compared with the unweighted mean of their observed yields. Area shares of the varieties within a field are not recorded, so the means could not be area-weighted; this is a limitation, since a minor variety counts as much as the main one.
- The same 22 partitions are used for every method. Learning curve: for each k in 1, 2, 3, 4, 6, 8, 12, 16 and 20, draw 25 random subsets of k training field-years (all 22 when k = 1), fit every method on the subset and score on the field-years left out; bands are the interquartile range of the 25 scores. Bootstrap: 50 resamples of the 22 field-years with replacement, each refitted. Random seed 20260926 throughout.

The post hoc missing-data variant was evaluated on the same dataset that revealed the problem with the default; it is a diagnosis, not an independent validation of a revised algorithm.""")
rep("Metrics are summarised by four numbers.", "Metrics are summarised by four numbers.")  # no-op guard
rep("The Nash-Sutcliffe efficiency (NSE) compares a method with the simplest possible prediction, the mean of all observed yields: 1 is a perfect prediction, 0 means the method does no better than that mean, and a negative value means it does worse.",
    "The Nash-Sutcliffe efficiency (NSE) compares a method with the simplest possible prediction, the mean of all observed yields: 1 is a perfect prediction, 0 means the method does no better than that mean, and a negative value means it does worse. The NSE reference is the overall observed mean, whereas the farm-mean baseline in each fold uses the training-set mean; the two differ by one field-year's contribution, which is why the farm-mean baseline itself has an NSE slightly below zero.")

# new 2.8 after 2.7 (before Section 3)
rep("## 3. Results", """### 2.8 Data quality screening and reproducibility

Operational yield maps arrive with defects that a research dataset would not have, and the way they are screened changes the result. Two quality levels are therefore reported. All operational records uses every field-year the plugin's scan accepted. Quality-screened records additionally excludes field-years whose field-mean potato yield exceeds 80 t/ha, above the crop's attainable yield in Sweden and so a probable monitor calibration or unit error; three field-years met that rule. For the index, a harvest map enters only if it covers at least 300 grid cells and its field median is positive, and a map whose values mix kilograms and tonnes per hectare within one year, detected as values more than two orders of magnitude from the field median, is converted to the majority unit before ranking; eight maps were converted, in one case for 466 of 1285 cells. The plugin's own import already removes implausible points and corrects sensor time lag, but has no headland, start-up or coverage filter; those would belong in a fuller pipeline and were not applied here.

Two software defects were found during the study and their status is traceable (Table 5): the irrigation loader summed overlapping passes as if each covered the whole field, and the fertiliser loader discarded imported journal rows with a source-table reference. The irrigation fix is in the exported data analysed here; the fertiliser rates were merged from the journal dump by the analysis script because the defect was found after the export, and the fixed loader yields the same records. Both fixes carry regression tests. The exported, anonymised tables, the analysis scripts, the protocol with its change log and the plugin at the analysed commit are archived together, and one command regenerates every table and figure from the tables.

## 3. Results""")

# ---------------------------------------------------------------- Section 3 wholesale
replace_between("## 3. Results\n", "## 4. Discussion", """## 3. Results

### 3.1 Dataset and exclusions

The Hörte database held yield maps for 36 fields and 117 field-years in total (Table 2). Of these, 22 field-years produced a usable training example, all potato and spread over ten of the harvest years 2015 to 2025 with none in 2022, giving 48 variety observations once fields planted with several varieties were split by variety (Figure 2a). The dominant reason for exclusion was the absence of a planting record in the harvest year, which accounted for 50 field-years and corresponds almost entirely to the cereal and oilseed rape seasons of the rotation, for which the farm logged harvest but not sowing (Figure 2b). A further 36 field-years had a planting record from an earlier year only, 7 had no usable yield value and 2 had no harvest data. Within the 48 observations, soil clay and humus were on file for one field and dated irrigation for every season from 2018 onwards; the five field-years of 2015 to 2017 have no irrigation record and were run as rainfed. Fertiliser rates in kilograms of nutrient per hectare existed for the seasons 2023 to 2025, imported from the farm's fertiliser-plan documents, plus one manual entry in 2018; after the season they covered 17 observations in 8 field-years for nitrogen (24 to 223 kg N/ha) and 9 observations in 4 field-years for potassium (135 to 355 kg K/ha). The remaining 14 field-years had no nutrient rate on file: the planter logged fertiliser on every potato pass as a flow percentage of its nominal setting, but that quantity is not a rate and did not enter the model.

Observed yields averaged 58 t/ha with a sample standard deviation of 16.5 t/ha across the 48 observations, from 27 to 100 t/ha. Within a field-year the varieties spanned a median of 11 t/ha and at most 37 t/ha, but this within-field-year variation was 23 % of the total variance; 77 % lay between field-years.

### 3.2 Performance of the implemented plugin

Under the plugin's implemented default a nutrient with no logged application is modelled with zero applied, so on the 31 observations without a nitrogen record and the 39 without a potassium record the uncalibrated potassium floor of 0.3 capped the estimate at 30 % of potential yield whatever the weather. At field-year level the literature defaults underpredicted by 42 t/ha with a typical error of 78 % of the mean yield (Table 3). Calibration, which can move only the nitrogen parameters, could raise that cap only by inflating potential yield: every fold returned the same triple, potential yield at its upper search bound of 112.5 t/ha, nitrogen factor 2.28 and floor 0.36, and the calibrated model still underpredicted by 21 t/ha with a typical error of 49 % and an efficiency of -2.5. The model attributed the limitation to potassium in 40 of 48 observations. This is the result a user of GeoDataFarm 3.5.0 would have obtained, and it is the pre-registered evaluation.

### 3.3 Diagnostic variant and baselines

Excluding an unlogged nutrient from the Liebig combination for that field-year, the post hoc variant, left the model water-limited on observations without a nutrient record and water- and nutrient-limited on those with one. Literature defaults then underpredicted by 31 t/ha with a typical error of 58 %, because the default potential yield of 45 t/ha is below what this farm harvests in a good year. Calibrating the three crop-level parameters removed the bias and brought the typical error to 31 %, a 47 % reduction, with a smaller miss than the defaults in 19 of 22 field-years (Figure 3a, b). It did not beat the training-set farm mean, whose typical error was 27 % and which the calibrated model out-predicted in only 12 of 22 field-years; both had negative efficiencies, -0.41 and -0.09. The pre-registered criterion, a 20 % reduction against the defaults together with a lower error than the farm mean, was therefore not met in either treatment. Fitting potential yield alone gave 32 %, so the two nitrogen parameters added little (Table 3).

The training-set same-variety mean was the strongest predictor evaluated: a typical error of 22 % of the mean yield and the only positive efficiency, +0.29, lower than the farm mean in 12 of 22 field-years (Figure 3d). Refitting potential yield per variety for the eight varieties that recur in at least two training field-years brought the model to 27 % and an efficiency of -0.06, level with the farm mean and better than the same-variety mean in only 10 of 22 field-years (Figure 3c). At the level of variety observations the per-variety fit gained nothing over the crop-level fit, because it improved some varieties and worsened others (Figure S2); its fitted potential yields ran from 77 t/ha for King Edward to 117 t/ha for Belana and rested on two to eight field-years each. These are predictive results: the variety label carried more out-of-sample information than the logged weather and management variables in this dataset, but the design does not separate the cultivar from the years, fields and management under which each cultivar was grown.

Split by record, the crop-level model had a typical error of 35 % on the 8 field-years with a nitrogen record and 29 % on the 14 without, while the farm mean had 26 % and 27 %. Split by period, the model was better than the farm mean on the 5 field-years of 2015 to 2017, 11 % against 21 %, and worse on the 17 from 2018 onwards, 35 % against 29 % (Table S3). The earlier seasons are the ones with no irrigation record, so the model ran them as rainfed and matched their yields with a water deficit it cannot verify; the seasons with recorded irrigation are where it fell behind. The pre-specified sensitivity runs confirm this: without the unrecorded seasons the model stayed at 35 % against 29 % for the farm mean, with the fitted potential yield unchanged at 89.8 t/ha, and at the quality-screened level, without the three field-years above 80 t/ha, every method improved but the gap widened, 29 % for the model and 25 % for the per-variety fit against 20 % for the farm mean and 18 % for the same-variety mean, with the fitted potential yield at 86 t/ha (Table 3, Table S4). Including the three implausible field-years thus reduced the model's disadvantage against the mean baselines. Recombining the fitted relative-yield terms multiplicatively instead of by the minimum, without refitting, gave 34 % with a bias of -5 t/ha against 31 % for the minimum, so the Liebig operator is not what holds the model back (Table S4).

### 3.4 Learning curve

With a single training field-year the three-parameter model had a median typical error of 21.2 t/ha on the remaining field-years, below the literature defaults at 34.5 t/ha but above the training-set mean of that same field-year at 18.2 t/ha (Figure 4a). The curve fell slowly and not monotonically, 22.0 at two, 20.1 at three, 18.6 at eight, 16.8 at sixteen and 17.4 at twenty training field-years, and only from sixteen on did it reach the training-set farm mean, which itself sat at 17 to 18 t/ha from three field-years on. The potential-yield-only variant followed within 1 t/ha up to twelve field-years and was worse above. The per-variety fit was indistinguishable from the crop-level fit until sixteen training field-years, because a variety needs two training field-years before it gets its own potential yield, and pulled ahead only at twenty, to 15.8 t/ha; the same-variety mean likewise matched the plain training mean below eight field-years and was the best predictor from sixteen on. Fitted potential yield from one training field-year ranged from 60 to 112 t/ha across the 22 possible choices, with a median of 89.8, and its interquartile range narrowed to 82 to 97 t/ha only at sixteen or more (Figure 4b). On this farm one season fixes potential yield to that season's level, and whatever a variety contributes takes most of the record to learn.

### 3.5 Parameter stability under resampling

A parameter is well determined when refitting it on different subsets of the data gives nearly the same value; three views are given, and they measure different things. The 22 leave-one-field-year-out folds share 20 of their 21 training field-years, and the fitted values can only fall on the search grid, whose fine steps are 7.6 t/ha, 0.24 and 0.08, so their agreement is partly numerical resolution: potential yield came out at 89.8 t/ha in 21 folds and 97.4 in one, the nitrogen factor at 1.68 in 18, the floor at 0.52 in 18 and at its lower bound of 0 in one (Figure 5). The 50 bootstrap samples, each drawing 22 field-years with replacement, measure predictive stability: potential yield had 5th, 50th and 95th percentiles of 82.3, 89.8 and 97.4 t/ha and never reached a search bound; the nitrogen factor 0.48, 1.68 and 2.04, never at a bound; the floor 0, 0.52 and 0.64, at its lower bound in 8 of 50 samples. The one-dimensional profiles of the objective, the minimum of the sum of squared errors over the other axis at the all-data fit, measure practical identifiability: the sum of squares stays within 5 % of its minimum for potential yield between 85 and 93 t/ha, for the floor between 0.45 and 0.55 at the fitted factor, and for the nitrogen factor from 1.38 up to the search bound of 3.0 (Figure S1, Table S4). Potential yield is thus relatively stable under resampling and determined to roughly plus or minus 10 % by the data; the nitrogen factor is not, and the floor's apparent precision in the profile depends on the factor being held at its fitted value. Eight field-years with a fertiliser rate do not determine two nitrogen parameters.

### 3.6 Model-attributed limiting factors

The limiting factor is reported here as the modelled term with the lowest relative yield when that term is below 0.95; it is the model's attribution, not an agronomically verified limitation, and the model's own label, which reads "none" whenever no nutrient is modelled, is not used. By this definition the calibrated model attributed limitation to water in 33 of 48 observations, nitrogen in 11, potassium in 1 and to nothing in 3 (Figure 6a). The water relative yield was below 0.95 in 20 of 22 field-years, lowest at 0.46 on a 2018 field with 108 mm of logged irrigation against 136 mm of rain, then 0.51 on a 2023 field with none logged, and 0.56 to 0.60 on the four field-years of 2015 and 2016 run as rainfed for want of a record (Figure 6b). Part of the attributed water limitation is therefore an artefact of the missing pre-2018 irrigation record; the sensitivity run without those seasons shows that this does not move the fitted potential yield, but the water term cannot be validated on them. Nitrogen was attributed in all 8 observations of 2025, 6 of them on one field whose journal recorded only a 24 kg N/ha top-dressing and not the planting application, in 2 observations of 2018 with a single 60 kg N/ha entry and in 1 of 2024; those attributions reflect the record, not the crop.

### 3.7 Within-field productivity index

Figure 7 lays out which fields had a yield map in which year and which consecutive pairs could be scored. Thirty pairs of consecutive harvest years on 19 fields were on file; 21 pairs on 15 fields had enough cells with both maps to be scored, and 13 of these, on 8 fields, also had a soil layer: EM38 conductivity at one or two depths on 7 fields and laboratory sampling on one. The EM38 surveys date from 2016 to 2019 and were used unfiltered after removal of the no-data value; the laboratory layers are the 2018 sampling. Because the farm rotates potato with cereals and oilseed rape, 20 of the 21 pairs cross a crop boundary: 11 run from potato to a cereal or rape, 6 the other way, 3 from cereal to cereal and one from potato to potato; the crop labels are inferred from yield magnitude, since the cereal seasons have no planting record.

Year-to-year rank persistence. The index built from the previous season's yield map alone is a monotone transform of that map, so its rank correlation with the next season's map measures how much of the within-field ranking persists across the rotation, not any property of the index. That correlation had a median of 0.18 (interquartile range 0.08 to 0.32) over the 21 pairs, was positive in 19 and above 0.2 in 9; aggregated to one median per field it was 0.14 over 15 fields (Table 4). The top fifth of the field by previous yield out-yielded the bottom fifth by a median of 9 % of the field mean. The correlation was highest from cereal to cereal (0.28, n = 3), intermediate from potato to cereal (0.18, n = 11) and lowest from cereal to potato (0.07, n = 6). Figure 8 shows the pair at the median correlation.

Combining layers. On the 13 pairs with a soil layer the yield-only correlation was 0.15 (0.08 to 0.24). The plugin's default, one weight per layer, gave -0.03 (-0.13 to 0.11) on the same pairs and was lower than the yield-only index in 12 of the 13 (Figure 9, Table 4); one weight per layer group gave -0.01 and a z-score average -0.01, each also lower in 12 of 13, and the soil-only index -0.09. The soil layers were not without association: conductivity correlated with the next season's yield at a median of -0.15 across the 17 field-year and depth combinations, positive in 4, from -0.42 on one field to +0.33 and +0.62 on another, while the nine laboratory layers on the sampled field stayed within -0.17 to +0.17. Whether that association adds anything beyond the previous yield map is the relevant question, and the answer in this dataset is no: after the next season's yield rank was regressed on the previous season's rank, the conductivity layers correlated with the residual at a median absolute value of 0.11, above 0.2 in 3 of 17 cases, and the laboratory layers at 0.11 with a maximum of 0.15 (Table S5). The post hoc variant that weights each layer by its absolute rank correlation with the previous yield map, reversing the rank of a negatively associated layer, reached 0.15 (0.08 to 0.22), lower than yield-only in 5 of 13 pairs; it recovers approximately the yield-only level and no more, as expected of weights constructed to agree with the yield map. Soil weights of 0.5 and 2 and three or seven classes moved the default index's correlation by less than 0.03 (Table S5). The class-separation test on the spatially thinned subsample is reported in Table S5 only, since its outcome tracked the number of cells left after thinning rather than the index.

""")

# ---------------------------------------------------------------- discussion edits
rep("### 4.1 How much calibration buys, and where it stops helping\n\nBy the criterion fixed before the analysis, calibration was not useful on this farm.",
    "### 4.1 How much calibration buys, and where it stops helping\n\nBy the criterion fixed before the analysis, calibration was not useful on this farm, under either treatment of a missing nutrient record.")
rep("Why the farm mean is so hard to beat is the more useful question, and the variety results give half of the answer. The single best predictor in the study was the mean yield of the same variety in other seasons, at 22 % typical error against 27 % for the farm mean, which says that a large part of the between-field-year variance on this farm is the farmer's choice of variety: Belana and Queen Anne yield around 70 t/ha here, Fontane and Solist under 50.",
    "Why the farm mean is so hard to beat is the more useful question, and the variety results give half of the answer. The single best predictor in the study was the same-variety mean, at 22 % typical error against 27 % for the farm mean, which says that the variety label carries much of the between-field-year predictive information on this farm: Belana and Queen Anne average around 70 t/ha here, Fontane and Solist under 50. This is a predictive finding, not a causal one. Variety is confounded with the years, fields and soils on which each variety was grown, with seed size, in-row spacing and fertiliser flow, which the farmer sets per variety, and with irrigation; thirteen of the twenty-one varieties occur in a single field-year, and the paired advantage of the same-variety mean over the farm mean, 12 of 22 field-years, is itself modest. A hierarchical model with field-year and variety effects would sharpen but not resolve this on 22 field-years.")
rep("The honest reading is that on this farm the records support a yield-level correction, per crop or per variety, and little more, and that the model's remaining value lies in the attribution and the counterfactual, which a mean cannot provide, provided the attribution is not driven by a missing record. A rainfed farm, or one whose irrigation, fertiliser and soil records are complete across the seasons, is where the water and nutrient terms could separate the model from the mean, and that is where this study should be repeated.",
    "The honest reading is that on this farm the records support a yield-level correction, per crop or per variety, and little more, and that the model's remaining value, if any, lies in attribution and in comparing management options within a season, which a mean cannot provide; that scenario use was not tested here and remains a claim about the model's purpose, not a demonstrated capability. A rainfed farm, or one whose irrigation, fertiliser and soil records are complete across the seasons, is where the water and nutrient terms could separate the model from the mean, and that is where this study should be repeated. The recombination of the fitted terms multiplicatively instead of by the minimum changed the error by 3 percentage points, so the choice of the Liebig operator is not what limits the model here; the inputs are.")
rep("For a farmer reading the fitted values, the practical rules are that potential yield needs several seasons, not one, since a single season fixes it to that season's level, that the nitrogen parameters are only as good as the number of seasons with a complete rate, and that the plugin should say so: a fit should report how many field-years with a rate it rests on, an unlogged nutrient should be excluded from the season estimate rather than floored, and an unlogged irrigation season should be marked as unknown rather than run as rainfed. These are small changes in code and large in consequence.",
    "For a farmer reading the fitted values, the practical rules are that potential yield needs several seasons, not one, since a single season fixes it to that season's level, and that the nitrogen parameters are only as good as the number of seasons with a complete rate. The plugin should act on this rather than report it: offer the nitrogen parameters for calibration only when, say, five or more field-years carry a complete rate and otherwise fit potential yield alone; store and update potential yield per variety, which the farm's own records determine better than any crop-level value, falling back to the crop value for a variety with fewer than two seasons; exclude an unlogged nutrient from the season estimate rather than floor it; mark an unlogged irrigation season as unknown rather than run it as rainfed; and, where no soil texture is on file, say that the water term runs on a texture default rather than block calibration, since potential yield can still be learnt. These are small changes in code and large in consequence.")
rep("The model uses gridded reanalysis-based weather from Open-Meteo rather than station data, because the plugin must work anywhere its users farm. For a seasonal water balance this is adequate, but the nitrogen leaching term depends on rain within days of an application, where gridded products smooth local convective events, and the field-scale irrigation record, now area-weighted, is the only locally measured water input. A comparison of Open-Meteo against the nearest national station for the days after each application was not made in this study and is the obvious next check.",
    "The model uses gridded reanalysis-based weather from Open-Meteo rather than station data, because the plugin must work anywhere its users farm. The seasonal aggregation may reduce the sensitivity to day-scale weather errors, but its adequacy was not evaluated against station observations here, and the nitrogen leaching term depends on rain within days of an application, where gridded products smooth local convective events; the field-scale irrigation record, now area-weighted, is the only locally measured water input. A comparison of Open-Meteo against the nearest national station for the days after each application was not made in this study and is the obvious next check.")
rep("### 4.4 Fertility index\n\nThe positive result of Section 3.6 is a result about the farm, not about the index:",
    "### 4.4 Within-field productivity index\n\nThe plugin calls this its fertility index; the paper calls it a within-field productivity index, because historical yield and EM38 conductivity do not measure fertility and their associations with yield ran in both directions. The positive result of Section 3.7 is a result about the farm, not about the index:")
rep("Potato yield on this farm varies mainly with variety, seed spacing and fertiliser flow, all of which the farmer varies deliberately along planter passes, so a cereal map from the year before is a poor guide to where the next potato crop will yield.",
    "On this farm variety, seed spacing and fertiliser flow are set per planter pass, so a potato map carries management structure that a cereal map from the year before cannot anticipate; this is a plausible reason for the low cereal-to-potato persistence, not one tested here.")
rep("and it is lowest into potato, where the previous potato maps on this farm also carry the planter's deliberate variety, spacing and fertiliser-flow strips (Figure 8, first panel).",
    "and it is lowest into potato.")
rep("Weighting each source by its association with the previous yield map, and reversing the rank of a negatively associated source, recovered the yield-only level, which shows that the loss is a weighting and sign problem rather than an intrinsic one, and that a source can only be added safely when its direction has been checked against a yield map on that field. A z-score average did no better than the percentile rank, so the normalisation is not the issue.",
    "Weighting each layer by its association with the previous yield map, and reversing the rank of a negatively associated layer, recovered approximately the yield-only level, which shows that the loss is a weighting and sign problem; it does not show that the soil layers add information, and the residual analysis says they did not in this dataset. The direction of a conductivity layer's association may itself depend on the crop, the soil moisture at the time of the survey, topography and the survey year, so it should not be read as a property of the soil variable. A z-score average did no better than the percentile rank, so the normalisation is not the issue; the question is whether unsupervised combination of heterogeneous layers, by rank averaging or by the k-means and fuzzy c-means clustering that dominate the literature (Heidari et al., 2026), is sound at all without a yield map on the same field to check each layer's sign against. Three questions should be kept apart: equal weighting degrades the yield-only signal, yes, in this dataset; sign-aware weighting avoids most of the degradation, yes; soil layers add predictive information beyond the previous yield map, not demonstrated.")
rep("The plugin should therefore not offer equal weights as a default, should show the sign and strength of each source's association with the most recent yield map before combining, and should report each source's coefficient of variation so a user can see when the percentile stretch of a near-uniform source is artificial.",
    "The plugin should therefore not offer equal weights as a default, should show the sign and strength of each layer's association with the most recent yield map before combining, and should report each layer's coefficient of variation so a user can see when the percentile stretch of a near-uniform layer is artificial. The class-separation test proved too dependent on the thinning procedure to carry weight and is reported only in the supplement; descriptive measures, the rank correlation and the top-minus-bottom yield gap, are the honest summary at this sample size.")
rep("### 4.5 Limitations\n\nThe study rests on one farm. That was a deliberate first step,",
    "### 4.5 Limitations\n\nThe study rests on one farm and is a diagnostic case study, not a general evaluation; its results are hypothesis-generating. That was a deliberate first step,")
rep("The next step is to constrain the crop-development curve with observed canopy data. Sentinel-2 leaf-area retrievals are achievable at useful accuracy in this region (Thapa et al., 2026) and assimilation into simple crop models has been demonstrated (Bouras et al., 2023); the plugin's satellite tab already fetches the required bands.",
    "The next step is to constrain the crop-development curve with observed canopy data. Sentinel-2 leaf-area retrievals are achievable at useful accuracy in this region (Thapa et al., 2026) and assimilation into simple crop models has been demonstrated (Bouras et al., 2023); the plugin's satellite tab already fetches the required bands. Canopy data would address within-season development and within-field pattern, which neither the harvest-calibrated model nor the index captures well here, but it would not replace the harvest record for the yield level: an assimilated leaf-area index still needs a potential yield and a harvest index to become tonnes, and those are what the farm's own records teach.")

# ---------------------------------------------------------------- conclusions wholesale
replace_between("## 5. Conclusions\n", "## Declarations", """## 5. Conclusions

This single-farm diagnostic evaluation of a simple crop model and a within-field productivity index inside an open-source FMIS supports four conclusions, each a finding on this farm's records and a hypothesis for others.

1. The plugin's implemented treatment of a missing nutrient record, zero applied, made the crop model degenerate: the unlogged potassium floor capped every estimate, calibration drove potential yield to its search bound, and the calibrated model kept a 21 t/ha bias. A missing record must be interpreted as unknown, for nutrients and for irrigation alike.

2. With that interpretation, calibration corrected the farm's yield level, halving the error of the literature defaults to 31 % of the mean yield, but did not beat a training-set farm mean at 27 %, and the same-variety mean at 22 % out-predicted every model variant. The variety label carried more out-of-sample information than the logged weather and management variables, a predictive finding that the observational design cannot separate from the years, fields and management under which each variety was grown.

3. Potential yield was relatively stable under resampling, with 90 % of bootstrap fits within 82 to 97 t/ha, whereas the nitrogen factor and floor spanned most of their search ranges on eight field-years with a fertiliser rate. A FMIS should fit potential yield per variety from the farm's records and offer the nitrogen parameters for calibration only when enough complete rates exist.

4. Equal weighting of heterogeneous spatial layers removed the weak year-to-year signal carried by the previous yield map; a sign-aware weighting recovered approximately the yield-only level, and the soil layers showed no predictive information beyond the previous map in this dataset.

GeoDataFarm 3.5.0, the model, the calibration workflow, the two defect fixes and the analysis scripts are available under an open licence at the repository and archived with a DOI.

""")

# ---------------------------------------------------------------- declarations
rep("Competing interests: the author develops GeoDataFarm and sells the licence key that unlocks the crop-simulation page evaluated in this paper. [Declare any family, ownership or advisory relationship between the author and the study farm.]",
    "Competing interests: the author develops GeoDataFarm and sells the licence key that unlocks the crop-simulation page evaluated in this paper. [Declare any family, ownership or advisory relationship between the author and the study farm; state who approved the use of the farm's data; state whether any independent party verified the analysis scripts; state whether the study was covered by an institutional data or ethics review.] No independent party has verified the analysis scripts to date; the scripts and anonymised tables are archived so that this can be done.")
rep("Data availability: anonymised field-year tables, cross-validation outputs and grid-cell tables are provided as supplementary CSV files.",
    "Data availability: anonymised field-year tables, cross-validation outputs and grid-cell tables are provided as supplementary CSV files and are sufficient to regenerate every table and figure with the archived scripts.")

# ---------------------------------------------------------------- terminology sweep
s = s.replace("fertility index", "productivity index").replace("Fertility index", "Productivity index")
s = s.replace("the plugin's percentile-rank productivity index", "the plugin's percentile-rank productivity index (its \"fertility index\")", 1)
rep("### 2.4 Productivity index", "### 2.4 Productivity index (the plugin's fertility index)")
rep("- Table 4. Productivity-index sensitivity.", "- Table 4. Productivity-index variants.\n- Table 5. Software defects found during the study: status, fix and traceability.")

open(p, 'w', encoding='utf-8').write(s)
print('patched; missing anchors:', len(missing))
for m in missing:
    print('  MISSING:', m)
