"""The drop-down arrow on this plugin's combo boxes.

Every .ui file in the plugin carries the same stylesheet, and it styles
``QComboBox`` with a border and a flat ``::drop-down``. Qt's rule is that
once a combo box is styled that way the base style stops drawing the
arrow, and it only comes back if the stylesheet supplies one - so every
combo box in the plugin has been rendering as a plain rectangle, in Qt5
and Qt6 alike. A drop-down that looks like a text box does not get
clicked, which matters most on the journal fields that offer what was
entered before (see :mod:`support_scripts.journal_fields`): the whole
point of those is that the user can see there is a list.

Qt gives no way to draw a chevron from a stylesheet - the CSS
border-triangle trick renders as a solid square here - so the arrow has
to be an image. That leaves the question of how a .ui file names one:

* A relative ``url()`` resolves against the process working directory,
  which a QGIS plugin has no say over.
* An absolute path cannot be written into a .ui that ships to other
  machines.
* The compiled Qt resource file (resources.py) would work, but it is
  generated by a tool that is no longer part of the PyQt6 distribution,
  and a static image cannot follow the user's colour theme anyway.

So the .ui files name the arrow through a :class:`QDir` search path -
``url(gdfarrow:combo_arrow.png)`` - and :func:`install` decides at
runtime where that points and draws the image there, in the palette's own
text colour. Verified to resolve under both PyQt5/Qt 5.15 and
PyQt6/Qt 6.8.

:func:`install` has to run before any of those .ui files is loaded, since
Qt resolves a stylesheet's urls when the sheet is applied - hence the
call from ``GeoDataFarm.__init__`` rather than from ``run()``. If it
fails or never runs, Qt simply finds no image and the combo boxes look
exactly as they did before, which is why nothing here raises.
"""
from qgis.PyQt.QtCore import QDir, QPointF, QStandardPaths, Qt
from qgis.PyQt.QtGui import (QBrush, QColor, QGuiApplication, QPainter, QPalette,
                             QPixmap, QPolygonF)

from .notifier import log as gdf_log

__author__ = 'Axel Horteborn'

# The search path prefix the .ui stylesheets use. Changing it means
# changing every .ui file, so it is deliberately unglamorous and specific.
SEARCH_PREFIX = 'gdfarrow'
FILE_NAME = 'combo_arrow.png'

# Matches the 20px ``::drop-down`` the stylesheets reserve, with room
# around it. Drawn at 2x and scaled down would be sharper on a hidpi
# screen, but Qt scales a stylesheet image itself and the chevron is
# three straight strokes, so the difference is not worth the complexity.
_SIZE = 14
_STROKE = 1.6


def install(cache_dir: "str | None" = None) -> "str | None":
    """Draws the arrow and points the ``gdfarrow:`` search path at it.

    Parameters
    ----------
    cache_dir: str, optional
        Where to write the image. Defaults to the user's cache location;
        passing one explicitly is for the tests.

    Returns
    -------
    str or None
        The path written, or None if it could not be - in which case the
        combo boxes keep the appearance they have always had rather than
        the plugin failing to load over an arrow.
    """
    try:
        directory = cache_dir or _cache_dir()
        if not directory:
            return None
        QDir().mkpath(directory)
        path = QDir(directory).filePath(FILE_NAME)
        if not _draw(path, _arrow_color()):
            return None
        QDir.addSearchPath(SEARCH_PREFIX, directory)
        return path
    except Exception as e:
        gdf_log.warning(f'Could not install the combo box arrow: {e}')
        return None


def _cache_dir() -> str:
    """The user's cache location, falling back to a temporary directory.

    Not the plugin's own ``img`` folder: that is the install directory,
    which is read-only on a system-wide install and would leave a file
    behind that no uninstall removes.
    """
    location = QStandardPaths.writableLocation(
        QStandardPaths.StandardLocation.CacheLocation)
    if not location:
        location = QDir.tempPath()
    return QDir(location).filePath('geodatafarm')


def _arrow_color() -> QColor:
    """The palette's own text colour, so the arrow follows a dark theme
    instead of turning into a dark smudge on a dark background.

    Read once, when the plugin loads - QGIS asks for a restart when the
    theme changes, so there is nothing to react to in between.
    """
    app = QGuiApplication.instance()
    if app is None:
        return QColor('#5a5a5a')
    color = app.palette().color(QPalette.ColorRole.WindowText)
    # Softened towards the background: a full-strength text colour reads
    # as another glyph next to the field's contents rather than as
    # furniture.
    color.setAlpha(190)
    return color


def _draw(path: str, color: QColor) -> bool:
    """Paints a chevron and saves it. Returns whether the file was
    written."""
    pixmap = QPixmap(_SIZE, _SIZE)
    pixmap.fill(Qt.GlobalColor.transparent)
    painter = QPainter(pixmap)
    try:
        painter.setRenderHint(QPainter.RenderHint.Antialiasing)
        pen = painter.pen()
        pen.setColor(color)
        pen.setWidthF(_STROKE)
        pen.setCapStyle(Qt.PenCapStyle.RoundCap)
        pen.setJoinStyle(Qt.PenJoinStyle.RoundJoin)
        painter.setPen(pen)
        painter.setBrush(QBrush(Qt.GlobalColor.transparent))
        middle = _SIZE / 2.0
        painter.drawPolyline(_chevron(middle))
    finally:
        # A QPainter still active when its QPixmap is saved writes nothing
        # and prints a warning, so this must end even if the drawing did
        # not.
        painter.end()
    return pixmap.save(path)


def _chevron(middle: float):
    """The three points of a downward chevron, centred on the pixmap."""
    return QPolygonF([QPointF(middle - 3.5, middle - 1.75),
                      QPointF(middle, middle + 1.75),
                      QPointF(middle + 3.5, middle - 1.75)])
