# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImportInput_dialog_base.ui'
#
# Created: Tue May 09 16:26:50 2017
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ImportInputDialogBase(object):
    def setupUi(self, ImportInputDialogBase):
        ImportInputDialogBase.setObjectName(_fromUtf8("ImportInputDialogBase"))
        ImportInputDialogBase.resize(744, 536)
        self.button_box = QtGui.QDialogButtonBox(ImportInputDialogBase)
        self.button_box.setGeometry(QtCore.QRect(110, 500, 231, 23))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtGui.QDialogButtonBox.Cancel)
        self.button_box.setCenterButtons(False)
        self.button_box.setObjectName(_fromUtf8("button_box"))
        self.add_input_file = QtGui.QPushButton(ImportInputDialogBase)
        self.add_input_file.setGeometry(QtCore.QRect(11, 10, 85, 23))
        self.add_input_file.setObjectName(_fromUtf8("add_input_file"))
        self.label = QtGui.QLabel(ImportInputDialogBase)
        self.label.setGeometry(QtCore.QRect(11, 90, 101, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.TWColumnNames = QtGui.QTableWidget(ImportInputDialogBase)
        self.TWColumnNames.setGeometry(QtCore.QRect(10, 111, 371, 221))
        self.TWColumnNames.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed)
        self.TWColumnNames.setObjectName(_fromUtf8("TWColumnNames"))
        self.TWColumnNames.setColumnCount(0)
        self.TWColumnNames.setRowCount(0)
        self.label_3 = QtGui.QLabel(ImportInputDialogBase)
        self.label_3.setGeometry(QtCore.QRect(419, 90, 181, 21))
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.TWtoParam = QtGui.QTableWidget(ImportInputDialogBase)
        self.TWtoParam.setGeometry(QtCore.QRect(429, 111, 171, 221))
        self.TWtoParam.setObjectName(_fromUtf8("TWtoParam"))
        self.TWtoParam.setColumnCount(0)
        self.TWtoParam.setRowCount(0)
        self.pButRem_Param = QtGui.QPushButton(ImportInputDialogBase)
        self.pButRem_Param.setGeometry(QtCore.QRect(390, 220, 31, 23))
        self.pButRem_Param.setObjectName(_fromUtf8("pButRem_Param"))
        self.pButAdd_Param = QtGui.QPushButton(ImportInputDialogBase)
        self.pButAdd_Param.setGeometry(QtCore.QRect(390, 170, 31, 23))
        self.pButAdd_Param.setObjectName(_fromUtf8("pButAdd_Param"))
        self.pButInsertDataIntoDB = QtGui.QPushButton(ImportInputDialogBase)
        self.pButInsertDataIntoDB.setEnabled(False)
        self.pButInsertDataIntoDB.setGeometry(QtCore.QRect(120, 500, 131, 23))
        self.pButInsertDataIntoDB.setObjectName(_fromUtf8("pButInsertDataIntoDB"))
        self.label_4 = QtGui.QLabel(ImportInputDialogBase)
        self.label_4.setGeometry(QtCore.QRect(20, 330, 491, 31))
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.pButContinue = QtGui.QPushButton(ImportInputDialogBase)
        self.pButContinue.setEnabled(False)
        self.pButContinue.setGeometry(QtCore.QRect(20, 360, 75, 23))
        self.pButContinue.setObjectName(_fromUtf8("pButContinue"))
        self.RBNoDate = QtGui.QRadioButton(ImportInputDialogBase)
        self.RBNoDate.setEnabled(False)
        self.RBNoDate.setGeometry(QtCore.QRect(10, 396, 131, 21))
        self.RBNoDate.setChecked(True)
        self.RBNoDate.setObjectName(_fromUtf8("RBNoDate"))
        self.RBYearOnly = QtGui.QRadioButton(ImportInputDialogBase)
        self.RBYearOnly.setEnabled(False)
        self.RBYearOnly.setGeometry(QtCore.QRect(140, 390, 141, 31))
        self.RBYearOnly.setChecked(False)
        self.RBYearOnly.setObjectName(_fromUtf8("RBYearOnly"))
        self.RBDateDiffTime = QtGui.QRadioButton(ImportInputDialogBase)
        self.RBDateDiffTime.setEnabled(False)
        self.RBDateDiffTime.setGeometry(QtCore.QRect(420, 370, 111, 41))
        self.RBDateDiffTime.setChecked(False)
        self.RBDateDiffTime.setObjectName(_fromUtf8("RBDateDiffTime"))
        self.year_only = QtGui.QLineEdit(ImportInputDialogBase)
        self.year_only.setEnabled(False)
        self.year_only.setGeometry(QtCore.QRect(160, 430, 113, 20))
        self.year_only.setObjectName(_fromUtf8("year_only"))
        self.label_5 = QtGui.QLabel(ImportInputDialogBase)
        self.label_5.setGeometry(QtCore.QRect(130, 430, 31, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.ComBDate = QtGui.QComboBox(ImportInputDialogBase)
        self.ComBDate.setGeometry(QtCore.QRect(410, 430, 111, 22))
        self.ComBDate.setEditable(True)
        self.ComBDate.setObjectName(_fromUtf8("ComBDate"))
        self.ComBTime = QtGui.QComboBox(ImportInputDialogBase)
        self.ComBTime.setGeometry(QtCore.QRect(410, 470, 111, 22))
        self.ComBTime.setEditable(True)
        self.ComBTime.setObjectName(_fromUtf8("ComBTime"))
        self.ComBDateTime = QtGui.QComboBox(ImportInputDialogBase)
        self.ComBDateTime.setGeometry(QtCore.QRect(532, 430, 111, 22))
        self.ComBDateTime.setEditable(True)
        self.ComBDateTime.setObjectName(_fromUtf8("ComBDateTime"))
        self.RBDateAndTime = QtGui.QRadioButton(ImportInputDialogBase)
        self.RBDateAndTime.setEnabled(False)
        self.RBDateAndTime.setGeometry(QtCore.QRect(530, 370, 101, 41))
        self.RBDateAndTime.setChecked(False)
        self.RBDateAndTime.setObjectName(_fromUtf8("RBDateAndTime"))
        self.label_6 = QtGui.QLabel(ImportInputDialogBase)
        self.label_6.setGeometry(QtCore.QRect(442, 410, 31, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(ImportInputDialogBase)
        self.label_7.setGeometry(QtCore.QRect(442, 450, 31, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.ComBDateOnly = QtGui.QComboBox(ImportInputDialogBase)
        self.ComBDateOnly.setGeometry(QtCore.QRect(290, 430, 111, 22))
        self.ComBDateOnly.setEditable(True)
        self.ComBDateOnly.setObjectName(_fromUtf8("ComBDateOnly"))
        self.RBDateOnly = QtGui.QRadioButton(ImportInputDialogBase)
        self.RBDateOnly.setEnabled(False)
        self.RBDateOnly.setGeometry(QtCore.QRect(300, 376, 111, 41))
        self.RBDateOnly.setChecked(False)
        self.RBDateOnly.setObjectName(_fromUtf8("RBDateOnly"))
        self.data_prefix = QtGui.QLineEdit(ImportInputDialogBase)
        self.data_prefix.setGeometry(QtCore.QRect(192, 10, 121, 20))
        self.data_prefix.setObjectName(_fromUtf8("data_prefix"))
        self.label_8 = QtGui.QLabel(ImportInputDialogBase)
        self.label_8.setGeometry(QtCore.QRect(130, 10, 61, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(ImportInputDialogBase)
        self.label_9.setGeometry(QtCore.QRect(320, 10, 181, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(ImportInputDialogBase)
        self.label_10.setGeometry(QtCore.QRect(20, 40, 121, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.EPSG = QtGui.QLineEdit(ImportInputDialogBase)
        self.EPSG.setGeometry(QtCore.QRect(150, 40, 61, 20))
        self.EPSG.setObjectName(_fromUtf8("EPSG"))
        self.label_11 = QtGui.QLabel(ImportInputDialogBase)
        self.label_11.setGeometry(QtCore.QRect(220, 40, 491, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.ComBNorth = QtGui.QComboBox(ImportInputDialogBase)
        self.ComBNorth.setGeometry(QtCore.QRect(50, 460, 111, 22))
        self.ComBNorth.setEditable(True)
        self.ComBNorth.setObjectName(_fromUtf8("ComBNorth"))
        self.ComBEast = QtGui.QComboBox(ImportInputDialogBase)
        self.ComBEast.setGeometry(QtCore.QRect(210, 460, 111, 22))
        self.ComBEast.setEditable(True)
        self.ComBEast.setObjectName(_fromUtf8("ComBEast"))
        self.label_12 = QtGui.QLabel(ImportInputDialogBase)
        self.label_12.setGeometry(QtCore.QRect(40, 460, 16, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(ImportInputDialogBase)
        self.label_13.setGeometry(QtCore.QRect(200, 460, 16, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.frame = QtGui.QFrame(ImportInputDialogBase)
        self.frame.setGeometry(QtCore.QRect(10, 70, 511, 21))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.RBComma = QtGui.QRadioButton(self.frame)
        self.RBComma.setGeometry(QtCore.QRect(80, 0, 61, 17))
        self.RBComma.setObjectName(_fromUtf8("RBComma"))
        self.RBSemi = QtGui.QRadioButton(self.frame)
        self.RBSemi.setGeometry(QtCore.QRect(160, 0, 82, 17))
        self.RBSemi.setObjectName(_fromUtf8("RBSemi"))
        self.RBTab = QtGui.QRadioButton(self.frame)
        self.RBTab.setGeometry(QtCore.QRect(250, 0, 41, 17))
        self.RBTab.setObjectName(_fromUtf8("RBTab"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 51, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.RBOwnSep = QtGui.QRadioButton(self.frame)
        self.RBOwnSep.setGeometry(QtCore.QRect(320, 0, 51, 17))
        self.RBOwnSep.setObjectName(_fromUtf8("RBOwnSep"))
        self.LEOwnSep = QtGui.QLineEdit(self.frame)
        self.LEOwnSep.setGeometry(QtCore.QRect(370, 0, 31, 20))
        self.LEOwnSep.setObjectName(_fromUtf8("LEOwnSep"))

        self.retranslateUi(ImportInputDialogBase)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("accepted()")), ImportInputDialogBase.accept)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("rejected()")), ImportInputDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(ImportInputDialogBase)

    def retranslateUi(self, ImportInputDialogBase):
        ImportInputDialogBase.setWindowTitle(_translate("ImportInputDialogBase", "Add indata to the model", None))
        self.add_input_file.setText(_translate("ImportInputDialogBase", "Add input file", None))
        self.label.setText(_translate("ImportInputDialogBase", "Columns in the file:", None))
        self.label_3.setText(_translate("ImportInputDialogBase", "Parameters that could be analysed:", None))
        self.pButRem_Param.setText(_translate("ImportInputDialogBase", "<--", None))
        self.pButAdd_Param.setText(_translate("ImportInputDialogBase", "-->", None))
        self.pButInsertDataIntoDB.setText(_translate("ImportInputDialogBase", "Add data to canvas", None))
        self.label_4.setText(_translate("ImportInputDialogBase", "Note that there need to be one (and only one) header column contating \"lat\" and one with \"lon\"", None))
        self.pButContinue.setText(_translate("ImportInputDialogBase", "Continue", None))
        self.RBNoDate.setText(_translate("ImportInputDialogBase", "Not date related data", None))
        self.RBYearOnly.setText(_translate("ImportInputDialogBase", "Only year related data \n"
" but no date column", None))
        self.RBDateDiffTime.setText(_translate("ImportInputDialogBase", "Date and time \n"
"are stored in two \n"
"different columns", None))
        self.label_5.setText(_translate("ImportInputDialogBase", "Year:", None))
        self.RBDateAndTime.setText(_translate("ImportInputDialogBase", "Date and time \n"
"are stored in \n"
"the same column", None))
        self.label_6.setText(_translate("ImportInputDialogBase", "Date:", None))
        self.label_7.setText(_translate("ImportInputDialogBase", "Time:", None))
        self.RBDateOnly.setText(_translate("ImportInputDialogBase", "Date stored in \n"
"following column", None))
        self.label_8.setText(_translate("ImportInputDialogBase", "Data prefix:", None))
        self.label_9.setText(_translate("ImportInputDialogBase", "(\"plant\", \"soiltype\", \"irrigation\" etc.)", None))
        self.label_10.setText(_translate("ImportInputDialogBase", "EPGS Coordinate system:", None))
        self.EPSG.setText(_translate("ImportInputDialogBase", "4326", None))
        self.label_11.setText(_translate("ImportInputDialogBase", "WGS 84 = 4326, RT90 2.5 gon V = 3021, UTM zone 32N = 32632, SWEREF99 TM = 3006 etc.", None))
        self.label_12.setText(_translate("ImportInputDialogBase", "N:", None))
        self.label_13.setText(_translate("ImportInputDialogBase", "E:", None))
        self.RBComma.setText(_translate("ImportInputDialogBase", "Comma", None))
        self.RBSemi.setText(_translate("ImportInputDialogBase", "Semicolon", None))
        self.RBTab.setText(_translate("ImportInputDialogBase", "Tab", None))
        self.label_2.setText(_translate("ImportInputDialogBase", "Separator", None))
        self.RBOwnSep.setText(_translate("ImportInputDialogBase", "Other:", None))

